---
- name: Configuring opendkim.conf
  template:
      src: opendkim.conf.j2
      dest: /etc/opendkim.conf

- name: Editing /etc/default/opendkim
  lineinfile:
      path: /etc/default/opendkim
      line: 'SOCKET="inet:12301@localhost"'
      state: present

- name: Creating openDKIM directories
  file:
      path: "/etc/{{ item }}"
      state: directory
  with_items:
      - "opendkim"
      - "opendkim/keys/"
      - "opendkim/keys/{{ mail_domain }}"

- name: Configuring openDKIM TrustedHosts
  template:
      src: Trustedhosts.j2
      dest: /etc/opendkim/TrustedHosts

- name: Configuring openDKIM KeyTable
  template:
      src: KeyTable.j2
      dest: /etc/opendkim/KeyTable


