- name: Updating package list
  apt:
    update_cache: yes
  fail:
    msg: "Target system is not debian based!"
  when: ansible_os_family == "Debian"

- name: Adding jessie-backports repo
  apt_repository:
    repo: deb http://ftp.debian.org/debian jessie-backports main
    update_cache: yes

- name: Installing the required packages
  apt:
    package: "{{ item }}"
    state: present
    with_items:
      - "{{ required_packages }}"
