- name: Updating package list
  apt:
      update_cache: yes

- name: Adding jessie-backports repo
  apt_repository:
    repo: deb http://ftp.debian.org/debian jessie-backports main
    update_cache: yes
  when: ansible_distribution == "Debian"

- name: Installing the required packages
  apt:
    package: "{{ item }}"
    state: present
  with_items:
    - "python-pip"
    - "mysql-server"
    - "postfix"
    - "postfix-mysql"
    - "dovecot-core"
    - "dovecot-imapd"
    - "dovecot-lmtpd"
    - "dovecot-mysql"
    - "opendkim"
    - "opendkim-tools"
    - "libmysqlclient-dev"
    - "python-dev"

- name: installing required pip modules
  pip:
    name: mysql-python

- name: Installing certbot from jessie-backports (debian)
  apt:
    package: certbot
    state: present
    default_release: jessie-backports
  when: ansible_distribution == "Debian"

- name: Installig certbot for PPA (ubuntu)
  apt_repository:
      repo: ppa:certbot/certbot
      update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: Installing certbot from PPA (ubuntu)
  apt:
      name: certbot
      state: installed
  when: ansible_distribution == "Ubuntu"
