- name: Creating user for dovecot
  user:
    name: "{{ mail_domain }}"
    createhome: yes
    comment: "User account for dovecot operations"

- name: Configuring dovecot.conf
  template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf

- name: Creating directories
  file:
    path: "/home/{{ mail_domain }}/{{ item }}"
    state: directory
  with_items:
      - "mail"
      - "mail/{{ mail_domain }}"

- name: Fixing permissions on directories
  file:
      path: "/home/{{ mail_domain }}/mail"
      owner: "{{ mail_domain }}"
      group: "{{ mail_domain }}"
      state: directory
      recurse: yes

